### ISSUE TITLE
Set up CI system

### ISSUE THREAD

**Issue by neverendingqs** [PokeAPI/pokeapi#354]
Needs to:
* Host local version of pokeapi
* Run [ditto](https://github.com/PokeAPI/ditto)
* Moves files to proper location?
* Set Netlify redirect rules
* Set up [headers file](https://www.netlify.com/docs/headers-and-basic-auth/)?

Tasks:
* [x] performance improvement addressed in #351
* [x] needs `ditto` in PyPi (https://github.com/PokeAPI/ditto/issues/4)
* [x] Connect to Netlify (https://github.com/PokeAPI/pokeapi/issues/352) (@neverendingqs)
* [x] Configure Netlify (see #356 for details) (@sargunv)

**Comment by sargunv** [comment]
Netlify's [continuous deployment](https://www.netlify.com/docs/continuous-deployment/) looks like it supports an arbitrary build command, so as long as the timeout is long enough it should be usable. I'd be happy to cook something up once pokeapi is fast.

**Comment by sargunv** [comment]
@neverendingqs Did you get the OSS Netlify team account set up? If not I'll start working on this on my personal account and migrate when we have it, but if it's already available then we can start right on that one.

At the moment I'm working on some refinements to Ditto that'll improve Ditto's handling of base URLs and make this CI job not need to run a `ditto clone` on every site update (since it can take some time to crawl all 10k objects).

**Comment by sargunv** [comment]
Sure, I'll add the ones that are related. Some aren't related -- I'm planning on eventually trying to leverage ditto's schema generation to auto-generate an easy to maintain successor to pokekotlin, and perhaps a whole suite of language specific clients.

**Comment by sargunv** [comment]
The API is up: https://pokeapi.netlify.com/api/v2/

[The config.](https://github.com/PokeAPI/ditto/blob/master/netlify.toml) It's deploying from [sargunv/ditto](https://github.com/sargunv/ditto) until Netlify gets approved by an admin to access this org. Atm, it redeploys whenever ditto is pushed, so once https://github.com/PokeAPI/ditto/issues/9 is complete it'll be always up to date.

**Comment by tdmalone** [comment]
Woww that’s amazing!! Awesome work @sargunv & @neverendingqs :D 

I’ve approved Netlify (and Docker Cloud) for access to the org.

I had in my head that the the API would deploy from the pokeapi repo, and we’d instead install ditto and generate static files in the build job. That way the API is naturally up-to-date on every push and ditto is treated as a library. Does it make more sense this way to have ditto as the gatekeeper? As part of PokeAPI/ditto#9 what would be the possibility of kicking off that job whenever pokeapi is pushed to?

**Comment by sargunv** [comment]
I just did it from ditto for now because it's not using anything outside ditto, but we can move the deploy config to be anywhere that makes sense. Maybe to its own repo. 

The update job can be set up to use a webhook to react to pushes. I'll work on the updater job next.

**Comment by neverendingqs** [comment]
@tdmalone - can you log into https://app.netlify.com/ and see if you have access? It should be under "All Teams" near the top left.

A Netlify representative told me it should be set up already, but I don't see it on my side. Perhaps only org admins can see it?

**Comment by tdmalone** [comment]
@neverendingqs Not there 😢 I can only see a team I set up for testing awhile ago:

![image](https://user-images.githubusercontent.com/900469/45332095-f2ac0a00-b5b1-11e8-995a-2cec6e6c955f.png)

(And I logged in with GitHub SSO just in case)

I tried going through _Create new team_ but that asks me to select from either the Pro or Business plan.

I'd be surprised if they used GitHub permissions for their team permissions. It'd be cool (and it's what Travis CI does), but given Netlify works with multiple VCS providers I would think it's unlikely?

I'm thinking they need to give you access and then you can add other team members from there...

**Comment by neverendingqs** [comment]
@sargunv - I have unchecked the last task for now until you can get it set up on the PokeAPI Netlify account. Feel free to change it around if you want to track that task a different way.

**Comment by sargunv** [comment]
I've transferred it to the PokeAPI Netlify account: https://app.netlify.com/sites/pokeapi/overview
